name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # Setup .npmrc file to publish to npm
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install dependencies
      run: yarn install
    - name: Deploy
      run: yarn run deploy
      env:
        GATSBY_PORTFOLIO_GITHUB_TOKEN: ${{ secrets.GH_GRAPHQL_TOKEN }}
