name: Pipeline

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - gh-pages
  pull_request:

jobs:

  build:
    name: Build Site
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          clean: true

      - uses: actions/setup-node@v1
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: yarn install

      - name: Build Site
        run: yarn run build
        env:
          GATSBY_PORTFOLIO_GITHUB_TOKEN: ${{ secrets.GH_GRAPHQL_TOKEN }}

      - name: Store build artifact
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: |
            public/*

  publish:
    if: contains(github.ref, 'main')
    name: Publish Site
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Download site
        uses: actions/download-artifact@v2
        with:
          name: build
          path: ./public
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
